name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-token: # github token
    description: 'Github Repo token'
    required: true
  target-commit-sha:
    description: 'Target commit SHA'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'